export enum NotificationType {
  POST_LIKE = "POST_LIKE",
  COMMENT_LIKE = "COMMENT_LIKE",
  COMMENT_ADDED = "COMMENT_ADDED",
  REPLY_ADDED = "REPLY_ADDED",
  FOLLOW_REQUEST = "FOLLOW_REQUEST",
  FOLLOW = "FOLLOW",
  FOLLOW_ACCEPTED = "FOLLOW_ACCEPTED",
  DM = "DM",
}
